### ISSUE TITLE
Does not work under High Sierra or Mojave

### ISSUE THREAD

**Issue by glv** [FlyingDiver/StokerX#1]
Are you planning to update StokerX to work with recent releases of macOS?  I still have a Mac mini running Sierra that I'm holding off on upgrading so I can still use StokerX with my egg.

**Comment by FlyingDiver** [comment]
I no longer have a working Stoker, so I’m not planning on doing any work on the app. That’s why I put it on GitHub. I would welcome updates from other developers.

**Comment by FlyingDiver** [comment]
I think the biggest problem is Xcode updates since it was last built.  Not just OS changes.

**Comment by glv** [comment]
Yes, that seems right … I tried to build it a while back and it wouldn't build at all.

**Comment by FlyingDiver** [comment]
And I see that Rock's has stopped making and selling Stokers.  So no hope of getting a new one and trying to make this work again.  :(

**Comment by FlyingDiver** [comment]
For whatever reason, it's working on Catalina.  Mostly.
